In [6]:
from astropy.io import fits
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import numpy as np
from astropy.table import Table

In [48]:
path = './../catalogs/'
file = Table.read(path+'VUGC_pPXF_2017_v2.fits')
file2 = Table.read(path+'VDGC_pPXF_2017_v2.fits')

In [148]:
one=file[file['ZCONF']==1]

In [152]:
one

<Table length=97>
  VCC   TARGTYPE GCSAT  ...  YLOW YHIGH             SPEC1DNAME            
bytes10  bytes7  bytes2 ... int16 int16              bytes40              
------- -------- ------ ... ----- ----- ----------------------------------
VCC1148      NUC      N ...    43    59    spec1d.vugc1.000.NUC001.fits.gz
    ---     GCXL      Y ...    15    27   spec1d.vugc1.004.GCXL003.fits.gz
    ---     GCXL      Y ...    20    30   spec1d.vugc1.006.GCXL007.fits.gz
    ---     GCXL      N ...    58    68   spec1d.vugc1.007.GCXL008.fits.gz
    ---     GCXL      N ...    41    51   spec1d.vugc1.009.GCXL011.fits.gz
    ---     GCXL      Y ...    12    22   spec1d.vugc1.010.GCXL012.fits.gz
    ---     GCXL      N ...    16    26   spec1d.vugc1.011.GCXL013.fits.gz
    ---     GCXL      N ...    12    22   spec1d.vugc1.012.GCXL015.fits.gz
    ---     GCXL      Y ...   214   224   spec1d.vugc1.013.GCXL016.fits.gz
    ---     GCXL      N ...    60    70   spec1d.vugc1.014.GCXL017.fits.gz
    ...      ...    ... ...   ...   ...                                ...
    ---      SGR      N ...    81    91   spec1d.vugc6.049.SGR0039.fits.gz
    ---      SGR      N ...   112   120   spec1d.vugc6.050.SGR0044.fits.gz
    ---      SGR      N ...    67    77   spec1d.vugc6.051.SGR0085.fits.gz
    ---      SGR      N ...    21    29   spec1d.vugc6.052.SGR0105.fits.gz
    ---      SGR      N ...     8    16   spec1d.vugc6.053.SGR0118.fits.gz
    ---      SGR      N ...     8    16   spec1d.vugc6.054.SGR0123.fits.gz
    ---      SGR      N ...    62    72   spec1d.vugc6.055.SGR0130.fits.gz
    ---      SER      N ...    46    53 spec1d.vugc6.056.serendip1.fits.gz
    ---      SGR      N ...    58    66   spec1d.vugc6.058.SGR0175.fits.gz
    ---      SGR      N ...   297   307   spec1d.vugc6.059.SGR0179.fits.gz

In [155]:
Y=one[one['GCSAT']=='Y']

In [156]:
Y

<Table length=25>
  VCC   TARGTYPE GCSAT    HOST  ...  YLOW YHIGH            SPEC1DNAME           
bytes10  bytes7  bytes2 bytes10 ... int16 int16             bytes40             
------- -------- ------ ------- ... ----- ----- --------------------------------
    ---     GCXL      Y  VLSB-B ...    15    27 spec1d.vugc1.004.GCXL003.fits.gz
    ---     GCXL      Y  VLSB-B ...    20    30 spec1d.vugc1.006.GCXL007.fits.gz
    ---     GCXL      Y  VLSB-B ...    12    22 spec1d.vugc1.010.GCXL012.fits.gz
    ---     GCXL      Y VCC1148 ...   214   224 spec1d.vugc1.013.GCXL016.fits.gz
    ---     GCXF      Y  VLSB-B ...    15    23 spec1d.vugc1.019.GCXF011.fits.gz
    ---     GCBL      Y VCC1153 ...    40    50 spec1d.vugc1.028.GCBL005.fits.gz
    ---     GCXL      Y  VLSB-D ...     4     7 spec1d.vugc5.001.GCXL001.fits.gz
    ---     GCXL      Y  VLSB-D ...    24    32 spec1d.vugc5.002.GCXL002.fits.gz
    ---     GCXL      Y  VLSB-D ...    55    63 spec1d.vugc5.003.GCXL003.fits.gz
    ---     GCXL      Y  VLSB-D ...    16    22 spec1d.vugc5.004.GCXL004.fits.gz
    ...      ...    ...     ... ...   ...   ...                              ...
    ---     GCXF      Y  VLSB-D ...    30    38 spec1d.vugc5.015.GCXF002.fits.gz
    ---     GCXF      Y  VLSB-D ...    22    30 spec1d.vugc5.019.GCXF008.fits.gz
    ---     GCBF      Y  VLSB-D ...    43    51 spec1d.vugc5.025.GCBF006.fits.gz
    ---     GCXL      Y VCC0615 ...    19    27 spec1d.vugc6.001.GCXL001.fits.gz
    ---     GCXL      Y VCC0615 ...    14    24 spec1d.vugc6.002.GCXL002.fits.gz
    ---     GCXL      Y VCC0615 ...    39    47 spec1d.vugc6.003.GCXL003.fits.gz
    ---     GCXL      Y VCC0615 ...    37    45 spec1d.vugc6.004.GCXL004.fits.gz
    ---     GCXF      Y VCC0615 ...   103   113 spec1d.vugc6.005.GCXF003.fits.gz
    ---     GCXF      Y VCC0615 ...    15    23 spec1d.vugc6.006.GCXF005.fits.gz
    ---     GCXF      Y VCC0615 ...    46    54 spec1d.vugc6.007.GCXF006.fits.gz

In [126]:
test = []
# test2 = []
test = file[file['ZCONF']==1]
test = test[test['GCSAT']== 'Y']
ind_VLSBB= test['HOST']== 'VLSB-B'
ind_VLSBD= test['HOST']== 'VLSB-D'
ind_VCC0615= test['HOST']== 'VCC0615'
# test2 = file2[file2['ZCONF']==1]
# test2 = file2[file2['GCSAT']== 'Y']


In [147]:

UDGGC = test[ind_VLSBB | ind_VLSBD | ind_VCC0615]

In [128]:
UDGGC

<Table length=23>
  VCC   TARGTYPE GCSAT    HOST  ...  YLOW YHIGH            SPEC1DNAME           
bytes10  bytes7  bytes2 bytes10 ... int16 int16             bytes40             
------- -------- ------ ------- ... ----- ----- --------------------------------
    ---     GCXL      Y  VLSB-B ...    15    27 spec1d.vugc1.004.GCXL003.fits.gz
    ---     GCXL      Y  VLSB-B ...    20    30 spec1d.vugc1.006.GCXL007.fits.gz
    ---     GCXL      Y  VLSB-B ...    12    22 spec1d.vugc1.010.GCXL012.fits.gz
    ---     GCXF      Y  VLSB-B ...    15    23 spec1d.vugc1.019.GCXF011.fits.gz
    ---     GCXL      Y  VLSB-D ...     4     7 spec1d.vugc5.001.GCXL001.fits.gz
    ---     GCXL      Y  VLSB-D ...    24    32 spec1d.vugc5.002.GCXL002.fits.gz
    ---     GCXL      Y  VLSB-D ...    55    63 spec1d.vugc5.003.GCXL003.fits.gz
    ---     GCXL      Y  VLSB-D ...    16    22 spec1d.vugc5.004.GCXL004.fits.gz
    ---     GCXL      Y  VLSB-D ...    72    82 spec1d.vugc5.006.GCXL007.fits.gz
    ---     GCXL      Y  VLSB-D ...    44    52 spec1d.vugc5.007.GCXL009.fits.gz
    ...      ...    ...     ... ...   ...   ...                              ...
    ---     GCXF      Y  VLSB-D ...    30    38 spec1d.vugc5.015.GCXF002.fits.gz
    ---     GCXF      Y  VLSB-D ...    22    30 spec1d.vugc5.019.GCXF008.fits.gz
    ---     GCBF      Y  VLSB-D ...    43    51 spec1d.vugc5.025.GCBF006.fits.gz
    ---     GCXL      Y VCC0615 ...    19    27 spec1d.vugc6.001.GCXL001.fits.gz
    ---     GCXL      Y VCC0615 ...    14    24 spec1d.vugc6.002.GCXL002.fits.gz
    ---     GCXL      Y VCC0615 ...    39    47 spec1d.vugc6.003.GCXL003.fits.gz
    ---     GCXL      Y VCC0615 ...    37    45 spec1d.vugc6.004.GCXL004.fits.gz
    ---     GCXF      Y VCC0615 ...   103   113 spec1d.vugc6.005.GCXF003.fits.gz
    ---     GCXF      Y VCC0615 ...    15    23 spec1d.vugc6.006.GCXF005.fits.gz
    ---     GCXF      Y VCC0615 ...    46    54 spec1d.vugc6.007.GCXF006.fits.gz

In [133]:
~ind_VLSBB

array([False, False, False,  True, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [134]:
ind_VLSBB

array([ True,  True,  True, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [142]:
~ind_VLSBB & ~ind_VLSBD & ~ind_VCC0615

array([False, False, False,  True, False,  True, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [143]:
opp=[~ind_VLSBB & ~ind_VLSBD & ~ind_VCC0615]

In [144]:
test[opp]

<Table length=2>
  VCC   TARGTYPE GCSAT    HOST  ...  YLOW YHIGH            SPEC1DNAME           
bytes10  bytes7  bytes2 bytes10 ... int16 int16             bytes40             
------- -------- ------ ------- ... ----- ----- --------------------------------
    ---     GCXL      Y VCC1148 ...   214   224 spec1d.vugc1.013.GCXL016.fits.gz
    ---     GCBL      Y VCC1153 ...    40    50 spec1d.vugc1.028.GCBL005.fits.gz